#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum anne_pro_keycodes {
    SOCD_S, //A->S
    SOCD_F //D->F
};
bool s_down = false;
bool f_down = false;


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_ESC, KC_TAB, KC_CAPS, KC_LSFT, KC_1, KC_Q, KC_A, KC_Z, KC_2, KC_W, SOCD_S, KC_X, KC_LBRC, KC_3, KC_E, KC_D, KC_C, KC_RBRC, KC_SPC, KC_LCTL, KC_4, KC_R, SOCD_F, KC_V, KC_LGUI, KC_BSPC, KC_LALT, KC_5, KC_T, KC_G, KC_B, MO(2), MO(1), KC_LCTL, KC_Y, KC_H, KC_N, MO(1), MO(2), KC_7, KC_U, KC_J, KC_M, KC_RGUI, KC_NO, KC_RALT, KC_8, KC_I, KC_K, KC_COMM, KC_LBRC, KC_BSPC, KC_RCTL, KC_9, KC_O, KC_L, KC_DOT, KC_RBRC, KC_0, KC_P, KC_SCLN, KC_SLSH, KC_EQL, KC_BSLS, KC_QUOT, KC_SCLN),
    [1] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_PGDN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_LEFT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_UP, KC_DOWN, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT(KC_F1, KC_TRNS, KC_TRNS, KC_TRNS, KC_F2, KC_TRNS, KC_TRNS, KC_TRNS, KC_F3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F5, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F6, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_F7, KC_TRNS, KC_F8, KC_P7, KC_P4, KC_P1, KC_TRNS, KC_TRNS, KC_NO, KC_P8, KC_P5, KC_P2, KC_P0, KC_TRNS, KC_TRNS, KC_NO, KC_P9, KC_P6, KC_P3, KC_PDOT, KC_TRNS, KC_F11, KC_MINS, KC_NO, KC_NO, KC_F12, KC_NO, KC_NO, KC_NO)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case SOCD_S:
            if (record->event.pressed) {
                if (f_down)
                {
                    unregister_code(KC_F);
                }
                register_code(KC_S);
                s_down = true;
            } else
            {
                unregister_code(KC_S);
                s_down = false;

                if (f_down) {
                    register_code(KC_F);
                }

            }
            return false;
            break;
        case SOCD_F:
            if (record->event.pressed)
            {
                if (s_down) {
                    unregister_code(KC_S);
                }
                register_code(KC_F);
                f_down = true;
            } else
            {
                unregister_code(KC_F);
                f_down = false;

                if (s_down)
                {
                    register_code(KC_S);
                }
            }
            return false;
            break;
    }
    return true;
}

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


